<?php require_once('config.php');
    session_start();
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="style.css">
    <style>
        .welcome-box {
            background-color: #6c757d;
            padding: 20px;
            border-radius: 10px;
            color: white;
            text-align: center;
        }
        .welcome-box a {
            margin: 5px;
        }
    </style>
</head>
<body>
    <header class="text-center p-4">
        <img src="HealthLink.png" alt="Healthcare Portal Logo" class="img-fluid">
    </header>
    <div class="container mt-5">
        <h1 class="text-center">Welcome to HealthLink</h1>
        <div class="row justify-content-center mt-4">
            <form method="GET" action="<?php echo htmlspecialchars($_SERVER["PHP_SELF"]); ?>">
                <div class="col-sm-4 col-lg-4 login-box" id="patientBox">
                    <!-- Patient Box -->
                    <p>Patient Portal</p>
                    <button class="btn btn-light btn-sm" name="signUpExpand">Sign Up</button>
                    <button class="btn btn-light btn-sm" name="loginExpand">Login</button>
                </div>
                <div class="col-sm-4 col-lg-4 login-box" id="doctorBox">
                    <!-- Doctor Box -->
                    <p>Doctor Login</p>
                    <button class="btn btn-light btn-sm" name="providerLoginExpand">Login</button>
                </div>
            </form>
            <?php
                if ($_SERVER["REQUEST_METHOD"] == "GET")
                {
                    $connection = new mysqli(DBHOST, DBUSER, DBPASS, DBNAME);
                    if ( mysqli_connect_errno() )
                                    {
                                        die( mysqli_connect_error() );
                                    }
                    if (isset($_GET['signUpExpand'])) {
                        // This code was partially generated by Chat-GPT
                        echo '
                        <div class="col-sm-4 col-lg-4 login-box" id="signupForm">
                            <form class="form-inner" method="GET" action="index.php">
                                <input name="username" type="username" class="form-control mb-2" placeholder="Username required">
                                <input name="password" type="password" class="form-control mb-2" placeholder="Password required">

                                <label for="first_name">First Name:</label>
                                <input type="text" id="first_name" name="first_name" required><br>
                                
                                <label for="last_name">Last Name:</label>
                                <input type="text" id="last_name" name="last_name" required><br>

                                <label for="high_blood_pressure">
                                    <input type="checkbox" id="high_blood_pressure" name="high_blood_pressure" value="1">
                                    High Blood Pressure
                                </label><br>
                                
                                <label for="diabetes">
                                    <input type="checkbox" id="diabetes" name="diabetes" value="1">
                                    Diabetes
                                </label><br>
                                
                                <label for="weight_gain">
                                    <input type="checkbox" id="weight_gain" name="weight_gain" value="1">
                                    Weight Gain
                                </label><br>
                                
                                <label for="heart_conditions">
                                    <input type="checkbox" id="heart_conditions" name="heart_conditions" value="1">
                                    Heart Conditions
                                </label><br>
                                
                                <label for="copd">
                                    <input type="checkbox" id="copd" name="copd" value="1">
                                    COPD
                                </label><br>
                                
                                <label for="sleep_apnea">
                                    <input type="checkbox" id="sleep_apnea" name="sleep_apnea" value="1">
                                    Sleep Apnea
                                </label><br>
                                
                                <label for="asthma">
                                    <input type="checkbox" id="asthma" name="asthma" value="1">
                                    Asthma
                                </label><br>

                                <button type="submit" class="btn btn-primary" name="patientSignup">Sign Up</button>
                            </form>
                        </div>
                        ';
                    } else if (isset($_GET['loginExpand'])) {
                        // Do something to give entry fields
                        echo '
                        <div class="col-sm-4 col-lg-4 login-box" id="loginForm">
                            <form class="form-inner" method="GET" action="index.php">
                                <input name="username" type="username" class="form-control mb-2" placeholder="Username required">
                                <input name="password" type="password" class="form-control mb-2" placeholder="Password required">
                                <button type="submit" class="btn btn-primary" name="patientLogin">Login</button>
                            </form>
                        </div>
                        ';
                    } else if (isset($_GET['providerLoginExpand'])) {
                        // Do something to give entry fields
                        echo '
                        <div class="col-sm-4 col-lg-4 login-box" id="doctorForm">
                            <form class="form-inner" method="GET" action="index.php">
                                <input name="username" type="username" class="form-control mb-2" placeholder="Username" required">
                                <input name="password" type="password" class="form-control mb-2" placeholder="Password" required>
                                <button type="submit" class="btn btn-primary" name="providerLogin">Login</button>
                            </form>
                            <p class="admin-info" style="font-size: 0.8rem;">If you do not have a login, please contact your hospital admin.</p>
                        </div>
                        ';
                    } else if (isset($_GET['providerLogin'])) {
                        $username = $_GET['username'];
                        $password = $_GET['password'];
                        $sql = "SELECT * FROM admin_signin WHERE '$username' = admin_Username AND '$password' = admin_Password";
                        if ($result = mysqli_query($connection, $sql)) {
                            if (mysqli_num_rows($result) > 0) {
                                $_SESSION['isAdmin'] = "true";
                                header('Location: patient_info.php');
                                exit();
                            } else {
                                echo "<div> Wrong credentials! </div>"; 
                            }
                            mysqli_free_result($result);
                        } else {
                            echo "<div> Wrong credentials! </div>"; 
                        }
                    } else if (isset($_GET['patientLogin'])) {
                        $username = $_GET['username'];
                        $password = $_GET['password'];
                        $sql = "SELECT * FROM patients_signin WHERE '$username' = patient_Username AND '$password' = patient_Password";
                        if ($result = mysqli_query($connection, $sql)) {
                            if (mysqli_num_rows($result) > 0) {
                                $_SESSION['isAdmin'] = "false";
                                $_SESSION['patientID'] = $username;
                                header('Location: patient_info.php');
                                exit();
                            } else {
                                echo "<div> Wrong credentials! </div>"; 
                            }
                            mysqli_free_result($result);
                        } else {
                            echo "<div> Wrong credentials! </div>"; 
                        }
                    } else if (isset($_GET['patientSignup'])) {
                        $username = $_GET['username'];
                        $password = $_GET['password'];
                        $first_name = $_GET['first_name'];
                        $last_name = $_GET['last_name'];

                        $high_blood_pressure = isset($_GET['high_blood_pressure']) ? "T" : "F";
                        $diabetes = isset($_GET['diabetes']) ? "T" : "F";
                        $weight_gain = isset($_GET['weight_gain']) ? "T" : "F";
                        $heart_conditions = isset($_GET['heart_conditions']) ? "T" : "F";
                        $copd = isset($_GET['copd']) ? "T" : "F";
                        $sleep_apnea = isset($_GET['sleep_apnea']) ? "T" : "F";
                        $asthma = isset($_GET['asthma']) ? "T" : "F";

                        $sql = "INSERT INTO PATIENTS_SIGNIN (Patient_Username, Patient_Password)
                                VALUES ('$username', '$password')";
                        $sql2 = "INSERT INTO PATIENTS 
                                VALUES ('$username', '$first_name', '$last_name', 
                                '$high_blood_pressure', '$diabetes', '$weight_gain', '$heart_conditions', '$copd', '$sleep_apnea', '$asthma')";
                        mysqli_query($connection, "START TRANSACTION");
                        $result1 = mysqli_query($connection, $sql);
                        $result2 = mysqli_query($connection, $sql2);
                        if ($result1 && $result2) {
                            mysqli_query($connection, "COMMIT");
                        } else {
                            mysqli_query($connection, "ROLLBACK");
                            echo "<div> Account Creation Failure! </div>";
                            exit();
                        }
                    }
                }
            ?>
    </div>
</body>
</html>


